In [2]:
#Word Embedding Techniques using Embedding Layer in Keras
from tensorflow.keras.preprocessing.text import one_hot

### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'python support various libraries',]

### Vocabulary size
voc_size=10000
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)
dim=10
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()
print(model.predict(embedded_docs))




[[25, 7152, 4876, 4427], [25, 7152, 4876, 3285], [25, 2995, 4876, 8171], [9224, 6993, 8547, 2985, 4654], [9224, 6993, 8547, 2985, 8464], [7677, 25, 2434, 4876, 9693], [3886, 7943, 5072, 9993]]
[[   0    0    0    0   25 7152 4876 4427]
 [   0    0    0    0   25 7152 4876 3285]
 [   0    0    0    0   25 2995 4876 8171]
 [   0    0    0 9224 6993 8547 2985 4654]
 [   0    0    0 9224 6993 8547 2985 8464]
 [   0    0    0 7677   25 2434 4876 9693]
 [   0    0    0    0 3886 7943 5072 9993]]
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
1/1 [==============================] - 0s 110ms/s